import { Moment } from 'moment';
import { ITrip } from 'app/shared/model/trip.model';
import { IInvoice } from 'app/shared/model/invoice.model';
import { IPayment } from 'app/shared/model/payment.model';
import { IEmail } from 'app/shared/model/email.model';
import { IContact } from 'app/shared/model/contact.model';
import { ITransactionsRecord } from 'app/shared/model/transactions-record.model';
import { IProductItem } from 'app/shared/model/product-item.model';
import { IAccounts } from 'app/shared/model/accounts.model';
import { Designation } from 'app/shared/model/enumerations/designation.model';
import { PreffredContactType } from 'app/shared/model/enumerations/preffred-contact-type.model';
import { CountryEnum } from 'app/shared/model/enumerations/country-enum.model';
import { ToggleStatus } from 'app/shared/model/enumerations/toggle-status.model';
import { CURRENCY } from 'app/shared/model/enumerations/currency.model';

export interface ICustomer {
  id?: number;
  company?: string;
  firstName?: string;
  lastName?: string;
  contactDesignation?: Designation;
  email?: string;
  phoneNumber?: number;
  phoneNumberExtention?: number;
  preffredContactType?: PreffredContactType;
  website?: string;
  alternateContactPerson?: string;
  alternateContactNumber?: number;
  alternatePhoneNumberExtention?: number;
  alternateContactEmail?: string;
  preferredContactTime?: string;
  fax?: number;
  address?: string;
  streetAddress?: string;
  city?: string;
  stateProvince?: string;
  country?: CountryEnum;
  postalCode?: string;
  dot?: string;
  mc?: number;
  taxId?: string;
  companyLogoContentType?: string;
  companyLogo?: any;
  customerSince?: string;
  notes?: string;
  contractContentType?: string;
  contract?: any;
  status?: ToggleStatus;
  preffredCurrency?: CURRENCY;
  payterms?: string;
  timeZone?: string;
  createdDate?: string;
  createdBy?: string;
  lastModifiedDate?: string;
  lastModifiedBy?: string;
  loadOrders?: ITrip[];
  invoices?: IInvoice[];
  payments?: IPayment[];
  emails?: IEmail[];
  morecontacts?: IContact[];
  transactionsRecords?: ITransactionsRecord[];
  charges?: IProductItem[];
  accounts?: IAccounts;
}

export const defaultValue: Readonly<ICustomer> = {};
